apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret-senior-script-kiddie-frontend
  namespace: senior-script-kiddie
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: <base64-encoded-config>
