apiVersion: v1
kind: Service
metadata:
  name: sskd-frontend-service
  namespace: sskd
  labels:
    app: sskd-frontend
spec:
  selector:
    app: sskd-frontend
  ports:
    number: 80
    targetPort: 8080
